logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    active: development

  output:
    ansi:
      enabled: always
server:
  address: 0.0.0.0
  port: ${PORT:8080}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    api-docs:
      path: /api-docs

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem